### ISSUE TITLE
Ouibounce version on npm is outdated

### ISSUE THREAD

**Issue by colinodell** [carlsednaoui/ouibounce#100]
Like #99, npm also shows the current version being **0.0.11** instead of **0.0.12**: https://www.npmjs.com/package/ouibounce

**Comment by rarkins** [comment]
Hi, can this be updated?

**Comment by carlsednaoui** [comment]
Should be all up to date. Sorry about the delay on this!

**Comment by carlsednaoui** [comment]
https://www.npmjs.com/package/ouibounce
