### ISSUE TITLE
Ouibounce keeps firing

### ISSUE THREAD

**Issue by Staalkoper** [carlsednaoui/ouibounce#106]
I'm trying to get Ouibounce to script to stop firing for x days after it has fired.
Looking into the documentation it shows that Agressive Mode is the answer for this, but I do not know how to implement this.

I thought that changing Ouibounce.js with
``aggressive   = config.aggressive || true,``
To
``aggressive   = config.aggressive || false,``
Would had been sufficient except it wasn´t (ofcourse it wouldn't - I guess =])

Can anyone help me further?

**Comment by christianesperar** [comment]
I think this is what you need https://github.com/carlsednaoui/ouibounce#cookie-expiration

**Comment by Staalkoper** [comment]
Thanks for the help Christiane!

I'm not very familiar with JS. 
Could you tell me where I should add 
``ouibounce(document.getElementById('ouibounce-modal'), { cookieExpire: 10 });``

**Comment by carlsednaoui** [comment]
@Staalkoper this looks to be resolved. Closing issue — please re-open if this is still a problem
