### ISSUE TITLE
On fire() function, add display:flex

### ISSUE THREAD

**Issue by paulhalfpenny** [carlsednaoui/ouibounce#113]
I'm using display:flex to position my modal centrally on the page, but this is overriden by this function: 

  function fire() {
    // You can use ouibounce without passing an element
    // https://github.com/carlsednaoui/ouibounce/issues/30
    if (el) el.style.display = 'block';
    disable();
  }

If you can change this line to: 

```
if (el) el.style.display = 'block | flex';
```

it works fine. I don't use Github typically, so no PR, but thought I would highlight it so you could add it in if you have time (or a better way of implementing this change!).

**Comment by Kalabasa** [comment]
I think a better way is to use `visibility` so clients can use any display style they want.
