### ISSUE TITLE
Different cookie per popup or per site section

### ISSUE THREAD

**Issue by JiveDig** [carlsednaoui/ouibounce#121]
First off, thanks for the amazing script!

I've created a little helper (WordPress) plugin that allows me to quickly create various popups with different styling, on different sections of the site. The issue i've run into is that the current script appears to only save 1 cookie, script wide. If I have 2 different popups (think: different optin or content per blog category), I need those 2 popups to be treated separately in regards to the cookie.

Maybe this is too annoying for users and shouldn't be considered, I haven't thought about it too long yet, i'm just trying to make this plugin really versatile.

Let me know your thoughts!

**Comment by JiveDig** [comment]
Turns out you can use a different cookie name per popup... then you can have different popups per section of your site. Cool!

**Comment by Isengo1989** [comment]
Could you share your answer? Much appreciated ;-)

**Comment by JiveDig** [comment]
See the 2nd snippet here. https://github.com/JiveDig/slim-popups/blob/master/README.md
I made a WordPress plugin to quickly setup popups.
