### ISSUE TITLE
Trouble getting  $('#ouibounce-modal').hide(); to trigger (magento/bootstrap)

### ISSUE THREAD

**Issue by kcr3d** [carlsednaoui/ouibounce#43]
Can't seem to get .hide() to work correctly. My website is www.leafandspoon.com (I've set up oiubounce at www.leafandspoon.com/ordering). I'll paste the JS below. I really want to use this utility; any help would be greatly appreciated. Thanks

 <script>
      // if you want to use the 'fire' or 'disable' fn,
      // you need to save OuiBounce to an object
      var _ouibounce = ouibounce(document.getElementById('ouibounce-modal'), {
        aggressive: true,
        timer: 0,
        callback: function() { console.log('ouibounce fired!'); }
      });

```
  $('body').on('click', function() {
    $('#ouibounce-modal').hide();
  });

  $('#ouibounce-modal .modal-footer').on('click', function() {
    $('#ouibounce-modal').hide();
  });

  $('#ouibounce-modal .modal').on('click', function(e) {
    e.stopPropagation();
  });
```

</script>

**Comment by takechi03** [comment]
ok i'm have solution this problem.

i use 
$('#landingpage, body').on('click',function(){
        $( ".action-close" ).trigger( "click" );
 });

you can use .
