### ISSUE TITLE
Create a few modal templates

### ISSUE THREAD

**Issue by carlsednaoui** [carlsednaoui/ouibounce#6]
Make it as easy as possible for people to use this library. Creating pre-generated / designed templates would help.

**Comment by joshuachestang** [comment]
Hey, sorry reopen this, but where are the templates exactly? I see them inside the readme but what about the actual code?

**Comment by joshuachestang** [comment]
Nevermind. Found them in: https://github.com/carlsednaoui/ouimodals

**Comment by carlsednaoui** [comment]
@joshuachestang I haven't had a chance to build the modals out. You can use the designs provided in the readme as inspiration to build your own though :)
