### ISSUE TITLE
Ouibounce is not being fired on production

### ISSUE THREAD

**Issue by fabiosl** [carlsednaoui/ouibounce#65]
Hi, 
Ouibounce is not being fired on my single-page application: http://onrocket.com.br. When I try it in localhost mode (index.html file) it works. Any hints?

**Comment by thoshikesh** [comment]
I'm facing the exact issue as well.

**Comment by anderskitson** [comment]
It's just cookies as far as I can tell, just delete this cookie in your resources tab when you are in inspect mode, and refresh, then it should fire again.
<img width="1341" alt="screen shot 2016-07-07 at 8 42 08 am" src="https://cloud.githubusercontent.com/assets/27952/16659411/c00bd94c-441e-11e6-94b0-d65d1de19f3a.png">
