### ISSUE TITLE
Twitter Bootstap Issue

### ISSUE THREAD

**Issue by muhammedtufekyapan** [carlsednaoui/ouibounce#66]
Hi,

We prepare a page and use ouibounce. We make every detail just same as examples. Modal open but we can't see. (We test it, when we inactive twitter bootstrap it work but when we use twitter bootstrap it won't work)

How can we fix that?

**Comment by PlushyObject** [comment]
@scofield-ua Why does that work?

**Comment by ibbatta** [comment]
@muhammedtufekyapan @carlsednaoui the main reason you can't see is for `.fade` class next `.modal`.
That class apply `opacity: 0` to you element.

@scofield-ua your solution doesn't work for me. Seems like doesn't reconize $(...) as an element

**Comment by CyrilKrylatov** [comment]
Well, I had some issues with Ouibounce & Bootstrap's modal.

Indeed, with only 

``` JS
ouibounce(false, {
        callback: function() {
            $('#your-modal-id').modal('show');
        }
  });
```

The `isDisabled()` function will be at true and if so, the ouibounce will never be fired.
So we have to make it false, like this: 

``` JS
document.addEventListener('DOMContentLoaded', function(){
    var _ouibounce = ouibounce(false, {
        aggressive: true,
        timer: 0,
        callback: function() {
            jQuery('#your-modal-id').modal('show');
        }
    });
});
```

Found the code here https://github.com/carlsednaoui/ouibounce/issues/92

Hop it helps!

Anyway @carlsednaoui that's a very nice plugin you made there, great great job. 👍

**Comment by EssiemLtd** [comment]
Amazing, thanks for this @DaPo .
However, the example gives ways for the user to exit by clicking an exit buttom. How do you incorporate this into the above script?

```javascript
        document.addEventListener('DOMContentLoaded', function(){       
            var _ouibounce = ouibounce(false, {
                aggressive: true,
                timer: 0,
                callback: function() {
                    jQuery('#your-modal-id').modal('show');
                }
            });
        
        $('body').on('click', function() {
          $('#ouibounce-modal').hide();
        });

        $('#ouibounce-modal .modal-footer').on('click', function() {
           $('#ouibounce-modal').hide();
        });
            
        $('#ouibounce-modal .modal').on('click', function(e) {
            e.stopPropagation();
        });
```

**Comment by CyrilKrylatov** [comment]
@EssiemLtd hello, I'm so so sorry, it's quite a while now, I barely remember what ouibounce does and I don't have much time to try to sort something out for you. 

But you maybe need to use [modal's event](https://getbootstrap.com/docs/4.3/components/modal/#events) first and search for "javascript detect click outside element" or something like this.

Have fun!
