### ISSUE TITLE
Ouibounce (exit popups) for smartphones and tablets

### ISSUE THREAD

**Issue by kevinweber** [carlsednaoui/ouibounce#74]
In another thread, @carlsednaoui mentioned that "there's no such thing as finger tracking yet". Let's discuss this and possible solutions to bring exit popups to smartphones and tablets.

Here is a behaviour that I've experienced as a typical behaviour before someone leaves a website on his mobile:
When the user finished reading, he scrolls back to the very top of the page to make the address bar appear and insert another address.

This behaviour (the behaviour that a user arrives at the very top of the page again) could be tracked and trigger an exit popup. What do you think of that? Any other ideas?

**Comment by tbuchok** [comment]
it would need to be tested, but @kevinweber's thought here is definitely interesting with regard to "scrolls up to get address bar"

in your desktop browser this would potentiallyl work with the "blur" event.

might be worth some examination by an intrepid soul ...

```js
;(function() {
  var thresholdMet = false;
  window.addEventListener('scroll', function(event) {
    thresholdMet = detectScrollThresholdSomehow(event);
    if (thresholdMet == false)
      return;
    var timer = setTimeout(function() {
        clearTimeout(timer);
        thresholdMet = false;
    }, SOME_REASONABLE_AMOUNT_OF_TIME);
  });
  window.addEventListener('blur', function(event) {
     if (thresholdMet)
       goGoOuiBounceExclamationMark();
   });
{());
```

hope that helps spur some ideas. :pizza:

**Comment by carlsednaoui** [comment]
I personally won't be working on this. Closing this issue. If anyone is interested on building this functionality pls hollar.

**Comment by simsketch** [comment]
Thought you guys might be interested in something like this. https://github.com/shahzam/DialogTriggerJS

I found it here: http://stackoverflow.com/a/38777449/1579789

> On some of my sites, I found that mobile exit intent often consists of a slight upward scroll before the user hits their back button. For example, users often scroll down the page quite a bit while consuming content, but when they're ready to leave they might scroll upwards slightly (say 5-10% of the page height), and then they'll go hit the back button or close the tab.

**Comment by will728** [comment]
Well to me, i still think, timing user time before displaying popup still works, but then on the other hand, here is the issue with timing, for example if it generally takes users 10 minutes to read the content of a page before they close it, if you set the exit intent for 10 minutes, some other users might just read the content of the page for less than 10 minutes, meaning users that read the content under 10 minutes will never see the exit, any i was able find a balance on this on my [web design site](http://zendbay.com) but i'm still researching ways to even make exit intent on mobile achievable. There is nothing impossible,
