### ISSUE TITLE
Sensitivity settings

### ISSUE THREAD

**Issue by brushbill** [carlsednaoui/ouibounce#78]
Hello,

could you kindly explain how is sensitivity setting is working ? 
Whatever I set it to, the popup pops then I go 1 pixel off the viewport.
And as I use it for exit surveys, I see that people often are not really exiting then they get the popup.

**Comment by carlsednaoui** [comment]
Hi @brushbill, ouibounce will always fire if you try to exit the viewport — that's the nature of the plugin.

To answer your question, sensitivity relies on this: https://developer.mozilla.org/en-US/docs/Web/Events/mouseleave 

This was added to prevent ouibounce from "firing too early" when certain elements had padding and what not.

Hope this helps,
