### ISSUE TITLE
Tablet

### ISSUE THREAD

**Issue by roblb** [carlsednaoui/ouibounce#84]
Is it possible to work on an implementation of this for touch devices so that it is activated after a certain amount of the page has been scrolled up?

**Comment by carlsednaoui** [comment]
Thanks for the suggestion @roblb. Unfortunately, this is not something we'll be pursuing on Ouibounce. You can find more info on this previous issue: https://github.com/carlsednaoui/ouibounce/issues/74

Please feel free to fork this project and add this functionality.
