### ISSUE TITLE
Feature request: Bounce Exchange style overlay

### ISSUE THREAD

**Issue by j-greig** [carlsednaoui/ouibounce#86]
Would you consider building an overlay style which mimics (the VERY expensive) http://www.bounceexchange.com/?

Thanks so much :)

James

**Comment by carlsednaoui** [comment]
_tl;dr: No._

Hi James,

Thanks for the suggestion! Ouibounce only handles the `business logic` of detecting _when_ to fire a modal.

How the modal looks and what it says is completely up to you. I haven't had a chance to write sample modals but I [did design a few](https://github.com/carlsednaoui/ouibounce#modal-inspiration) you can use as inspiration.

Hope this helps!
