### ISSUE TITLE
fire() should run the callback and check for previously disabled popup.

### ISSUE THREAD

**Issue by tomazzaman** [carlsednaoui/ouibounce#88]
If I manually try to call `fire()`, the callback is ignored completely, which is undesired - any particular reason why? Also, `fire()` should be able to check whether the popup is in a *disabled* state. If I created a pull request, would you be interested in merging?

Thanks!

**Comment by carlsednaoui** [comment]
@tomazzaman please do! would love to improve the fire() functionality.

Thanks so much for asking first and for taking charge of this! :pizza:

**Comment by tomazzaman** [comment]
I guess I can close this one now :)
