### ISSUE TITLE
No issue...just kudos!

### ISSUE THREAD

**Issue by marketbizpro** [carlsednaoui/ouibounce#92]
I really like this script!  It works wonders.

I noticed that some comments here were about folks wanting Twitter Bootstrap compliance.  

Just as a token of appreciation and, of course, kudos to the creator, I created something for everyone:

[Here's a free Bootstrap iteration with two demo styles!] (http://ignitionhub.com/bootbounce/index.html)

No big deal...but it does have two styles which have proven to be highly converting in the wild.

Some of the issues I've included are centering modals horizontally and vertically, opening one modal over another, pure bootstrap (except for a custom close button), high converting 'two choice' buttons, and more.

I hope everyone who sees this enjoys!

And thanks for creating the core code.

**Comment by carlsednaoui** [comment]
Thanks for the note and compliments.

I'd like to your page but, unfortunately, there's no way to download it without an email capture. That's a dealbreaker.

**Comment by marketbizpro** [comment]
I can give you the link to direct download, if you want?

**Comment by carlsednaoui** [comment]
Sure, that's be great!

**Comment by marketbizpro** [comment]
You may word the anchor text anyway you see fit.   The download page is here:  http://ignitionhub.com/bootbounce/thank-you.html  Or if you absolutely want the file download link, that is:  http://ignitionhub.s3.amazonaws.com/marketing_snippets/boot-bounce.zip ...whatever works for you. 

Thanks a bunch!  I hope it helps everyone...

**Comment by carlsednaoui** [comment]
Thanks @marketbizpro. I'll create a new issue for this and add it to the README when I get a chance.

**Comment by marketbizpro** [comment]
That's awesome!  Thank you...I hope everyone enjoys!

**Comment by marketbizpro** [comment]
Hey carlsednaoui/ouibounce,

I was asked to vouch for  people to join FounderDating - an invite-only network for entrepreneurs to connect with world-class advisors, potential cofounders and, of course, other entrepreneurs. There are really amazing people. You’re on my short list. I highly recommend applying no matter what stage you’re in.
                    
Apply here > http://members.founderdating.com/connect/?frvche=582702&s=

Check it out,
Phil

**Comment by carlsednaoui** [comment]
@marketbizpro thanks for the info but please don't promote other startups / services on this repo as this is not related to Ouibounce. As a heads up, I'm going to delete your above comment.
