### ISSUE TITLE
Submit to JSDelivr

### ISSUE THREAD

**Issue by bradvogel** [carlsednaoui/ouibounce#94]
Would be great to have this on JSDelivr so we can download it with our other scripts (via JSDelivr's concatenation feature).

See https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by carlsednaoui** [comment]
@bradvogel Just sent a PR :)

**Comment by carlsednaoui** [comment]
Done @bradvogel: 8d31243679bb1fc652896c43ddbda8bb7882c24c

**Comment by bradvogel** [comment]
Thanks!
