### ISSUE TITLE
Ouibounce conflict with jbetolo

### ISSUE THREAD

**Issue by madmaxy** [carlsednaoui/ouibounce#95]
Hi,

first of all, thx for the great solution.

My only problem is, if jbetolo is active, i get the overlay, but the modal-footer Button is not working.

Can i implement this script in one .js file?

 <script>

      // if you want to use the 'fire' or 'disable' fn,
      // you need to save OuiBounce to an object
      var _ouibounce = ouibounce(document.getElementById('ouibounce-modal'), {
        aggressive: true,
        timer: 0,
        callback: function() { console.log('ouibounce fired!'); }
      });

      $('body').on('click', function() {
        $('#ouibounce-modal').hide();
      });

      $('#ouibounce-modal .modal-footer').on('click', function() {
        $('#ouibounce-modal').hide();
      });

      $('#ouibounce-modal .modal').on('click', function(e) {
        e.stopPropagation();
      });
    </script>

**Comment by madmaxy** [comment]
// if you want to use the 'fire' or 'disable' fn,
      // you need to save OuiBounce to an object
      var _ouibounce = ouibounce(document.getElementById('ouibounce-modal'), {
        aggressive: true,
        timer: 0,
        callback: function() { console.log('ouibounce fired!'); }
      });

      $('body').on('click', function() {
        $('#ouibounce-modal').hide();
      });

      $('#ouibounce-modal .modal-footer').on('click', function() {
        $('#ouibounce-modal').hide();
      });

      $('#ouibounce-modal .modal').on('click', function(e) {
        e.stopPropagation();
      });

**Comment by carlsednaoui** [comment]
@madmaxy thanks for opening an issue. Unfortunately, I know nothing about jbetolo or Joomla. 

You mentioned
> modal-footer Button is not working.

This doesn't feel like a ouibounce-specific issue but more of an issue with the form you're using. If you took the demo form, that will certainly not work as it's for demo purposes only. May I suggest you open an issue on StackOverflow?

I will close this issue for now — let me know if there's anything I can do to be more useful.

Thanks,
