### ISSUE TITLE
ouibounce modal not firing from C# master page

### ISSUE THREAD

**Issue by sudipmisra** [carlsednaoui/ouibounce#97]
When I am attacing js and css in masterpage, the "ouibounce-modal" is not showing other inner divs. On exit, page become gray but no  <div class="modal"> is showing

**Comment by sudipmisra** [comment]
Adding   "display:block" helped

#ouibounce-modal .modal {
  display:block;
}

**Comment by carlsednaoui** [comment]
@sudipmisra this feels like a CSS or implementation error, correct?

As in, Ouibounce works as expected (the JS-based trigger). I'll close this issue unless you have a specific question I'm able to help you with.

Thanks

**Comment by sudipmisra** [comment]
Yes Ouibounce works as expected. Thanks for such a great API. Please close the issue.
