### ISSUE TITLE
Ouibounce version on cdnjs is outdated

### ISSUE THREAD

**Issue by yadomi** [carlsednaoui/ouibounce#99]
The last release on [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/ouibounce/0.0.11/ouibounce.js) is **0.0.11** but last release on Github is **0.0.12**

https://cdnjs.com/libraries/ouibounce

**Comment by yadomi** [comment]
@carlsednaoui up ? 

Do you plan to release `0.0.12` on cdnjs ?

Thanks

**Comment by carlsednaoui** [comment]
I do. It's supposed to be automatic. I haven't had a chance to look into
why it's not updating... sorry :(

**Comment by yadomi** [comment]
Ok, good to know and thanks for your reply :) 

Great tool btw :+1:

**Comment by jsieber-aca** [comment]
Just a heads up that cdnjs is still serving up the previous version.

**Comment by carlsednaoui** [comment]
Updated! https://cdnjs.com/libraries/ouibounce
